# https://hub.docker.com/_/alpine
FROM python:3.8.3-alpine 
# set environment variables
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

# install psycopg2 dependencies
RUN apk update \
    && apk add postgresql-dev gcc python3-dev musl-dev

# Install dependencies
RUN apk add --update --no-cache \
            ca-certificates \
            libpcap \
            libgcc libstdc++ \
            libressl3.1-libcrypto libressl3.1-libssl \
 && update-ca-certificates \
 && rm -rf /var/cache/apk/*

# Compile and install Nmap from sources
RUN apk add --update --no-cache --virtual .build-deps \
       libpcap-dev libressl-dev lua-dev linux-headers \
       autoconf g++ libtool make \
       curl \
&& curl -fL -o /tmp/nmap.tar.bz2 \
        https://nmap.org/dist/nmap-7.91.tar.bz2 \    
&& tar -xjf /tmp/nmap.tar.bz2 -C /tmp \
&& cd /tmp/nmap* \
&& ./configure \
       --prefix=/usr \
       --sysconfdir=/etc \
       --mandir=/usr/share/man \
       --infodir=/usr/share/info \
       --without-zenmap \
       --without-nmap-update \
       --with-openssl=/usr/lib \
       --with-liblua=/usr/include \
&& make \
&& make install \
&& apk del .build-deps \
&& rm -rf /var/cache/apk/* \
          /tmp/nmap*
RUN pip3 install --upgrade pip
RUN pip3 install requests
RUN pip3 install psycopg2
RUN pip install python-nmap

COPY . /scanner
RUN pip3 install -r /scanner/requirements.txt
RUN pip3 install netaddr

#ENTRYPOINT ["/bin/sh"]